name: CI

on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Действие'
        required: false
        default: 'nothing'
        type: choice
        options:
          - deploy
          - nothing
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/demo-flask:${{ github.sha }},${{ secrets.DOCKERHUB_USERNAME }}/demo-flask:latest
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: inputs.job == 'deploy'
    env:
      SERVER_IP: 5.35.87.129
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      -
        name: Generate docker-compose.yml
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.tpl.yml dev@${{ env.SERVER_IP }}:~/docker-compose.yml
          echo "WEB_CONTAINER_NAME=${{ secrets.DOCKERHUB_USERNAME }}/demo-flask:${{ github.sha }}" > vars.env
          scp -o StrictHostKeyChecking=no vars.env dev@${{ env.SERVER_IP }}:~/.env
      -
        name: Deploy with docker-compose
        run: |
          ssh -o StrictHostKeyChecking=no dev@${{ env.SERVER_IP }} 'cd ~ && docker-compose up -d'